# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TrafficViewer
                                 A QGIS plugin
 allows the user to add  googlemap traffic layer with realtime traffic data as a layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-12
        copyright            : (C) 2021 by Adel HADDID. Amine LARBI
        email                : adel.haddid@etu.usthb.dz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TrafficViewer class from file TrafficViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .traffic_viewer import TrafficViewer
    return TrafficViewer(iface)
