# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TrafficViewerDialog
                                 A QGIS plugin
 allows the user to add  googlemap traffic layer with realtime traffic data as a layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-12
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Adel HADDID. Amine LARBI
        email                : adel.haddid@etu.usthb.dz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'traffic_viewer_dialog_base.ui'))


class TrafficViewerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(TrafficViewerDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)


        self.spbStyle.valueChanged.connect(self.trafficViewer)
        self.cmbBaseMap.currentTextChanged.connect(self.trafficViewer)
        self.cmbLanguage.currentTextChanged.connect(self.trafficViewer)
        self.cmbAnnotation.currentTextChanged.connect(self.trafficViewer)
    def trafficViewer(self):
        ispbStyle = self.spbStyle.value()
        icmbBaseMap = self.cmbBaseMap.currentText()
        icmbLanguage = self.cmbLanguage.currentText()
        icmbAnnotation = self.cmbAnnotation.currentText()